// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Multi_Tracks_API.Models;

[Table("Artist")]
public partial class Artist
{
    [Key]
    public int artistID { get; set; }

    [Column(TypeName = "smalldatetime")]
    public DateTime dateCreation { get; set; }

    [Required]
    [StringLength(100)]

    public string title { get; set; }

    [Required]

    public string biography { get; set; }

    [Required]
    [StringLength(500)]

    public string imageURL { get; set; }

    [Required]
    [StringLength(500)]

    public string heroURL { get; set; }
}