// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Multi_Tracks_API.Models;

public partial class AssessmentStep
{
    [Key]
    public int stepID { get; set; }

    [Required]
    [StringLength(250)]
 
    public string text { get; set; }
}