// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Multi_Tracks_API.Models
{
    public partial class GetAssessmentStepsResult
    {
        public string text { get; set; }
    }
}
