// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Multi_Tracks_API.Models;

[Table("Song")]
public partial class Song
{
    [Key]
    public int songID { get; set; }

    [Column(TypeName = "smalldatetime")]
    public DateTime dateCreation { get; set; }

    public int albumID { get; set; }

    public int artistID { get; set; }

    [Required]
    [StringLength(255)]

    public string title { get; set; }

    [Column(TypeName = "decimal(6, 2)")]
    public decimal bpm { get; set; }

    [Required]
    [StringLength(10)]
   
    public string timeSignature { get; set; }

    public bool multitracks { get; set; }

    public bool customMix { get; set; }

    public bool chart { get; set; }

    public bool rehearsalMix { get; set; }

    public bool patches { get; set; }

    public bool songSpecificPatches { get; set; }

    public bool proPresenter { get; set; }
}