//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Album
{
    public int albumID { get; set; }
    public System.DateTime dateCreation { get; set; }
    public int artistID { get; set; }
    public string title { get; set; }
    public string imageURL { get; set; }
    public int year { get; set; }
}

public partial class Artist
{
    public int artistID { get; set; }
    public System.DateTime dateCreation { get; set; }
    public string title { get; set; }
    public string biography { get; set; }
    public string imageURL { get; set; }
    public string heroURL { get; set; }
}

public partial class AssessmentStep
{
    public int stepID { get; set; }
    public string text { get; set; }
}

public partial class C__RefactorLog
{
    public System.Guid OperationKey { get; set; }
}

public partial class Song
{
    public int songID { get; set; }
    public System.DateTime dateCreation { get; set; }
    public int albumID { get; set; }
    public int artistID { get; set; }
    public string title { get; set; }
    public decimal bpm { get; set; }
    public string timeSignature { get; set; }
    public bool multitracks { get; set; }
    public bool customMix { get; set; }
    public bool chart { get; set; }
    public bool rehearsalMix { get; set; }
    public bool patches { get; set; }
    public bool songSpecificPatches { get; set; }
    public bool proPresenter { get; set; }
}

public partial class GetAlbumDetails_Result
{
    public int albumID { get; set; }
    public System.DateTime dateCreation { get; set; }
    public int artistID { get; set; }
    public string title { get; set; }
    public string imageURL { get; set; }
    public int year { get; set; }
}

public partial class GetArtistDetails_Result
{
    public int artistID { get; set; }
    public System.DateTime dateCreation { get; set; }
    public string title { get; set; }
    public string biography { get; set; }
    public string imageURL { get; set; }
    public string heroURL { get; set; }
}

public partial class GetSongDetails_Result
{
    public int songID { get; set; }
    public System.DateTime dateCreation { get; set; }
    public int albumID { get; set; }
    public int artistID { get; set; }
    public string title { get; set; }
    public decimal bpm { get; set; }
    public string timeSignature { get; set; }
    public bool multitracks { get; set; }
    public bool customMix { get; set; }
    public bool chart { get; set; }
    public bool rehearsalMix { get; set; }
    public bool patches { get; set; }
    public bool songSpecificPatches { get; set; }
    public bool proPresenter { get; set; }
}
